-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.begeniler
(
    begeni_id serial NOT NULL,
    kullanici_id integer,
    haber_id integer,
    CONSTRAINT begeniler_pkey PRIMARY KEY (begeni_id)
);

CREATE TABLE IF NOT EXISTS public.etiketler
(
    etiket_id serial NOT NULL,
    adi character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT etiketler_pkey PRIMARY KEY (etiket_id)
);

CREATE TABLE IF NOT EXISTS public.gorseller
(
    gorsel_id serial NOT NULL,
    url character varying(30) COLLATE pg_catalog."default" NOT NULL,
    haber_id integer,
    CONSTRAINT gorseller_pkey PRIMARY KEY (gorsel_id)
);

CREATE TABLE IF NOT EXISTS public.haber
(
    haber_id serial NOT NULL,
    baslik character varying(50) COLLATE pg_catalog."default" NOT NULL,
    icerik character varying(30) COLLATE pg_catalog."default" NOT NULL,
    yazar_id integer,
    kategori_id integer,
    tarih date NOT NULL,
    guncelleme date NOT NULL,
    begeni_sayisi integer DEFAULT 0,
    yorum_sayisi integer DEFAULT 0,
    kullanici_id integer,
    CONSTRAINT haber_pkey PRIMARY KEY (haber_id)
);

CREATE TABLE IF NOT EXISTS public.haber_reklam
(
    haber_id integer NOT NULL,
    reklam_id integer NOT NULL,
    CONSTRAINT haber_reklam_pkey PRIMARY KEY (haber_id, reklam_id)
);

CREATE TABLE IF NOT EXISTS public.haberetiket
(
    haber_id integer,
    etiket_id integer
);

CREATE TABLE IF NOT EXISTS public.kategoriler
(
    kategori_id serial NOT NULL,
    "kategoriAdi" character varying(15) COLLATE pg_catalog."default",
    CONSTRAINT kategoriler_pkey PRIMARY KEY (kategori_id)
);

CREATE TABLE IF NOT EXISTS public.kullanici
(
    kullanici_id serial NOT NULL,
    kullaniciadi character varying(15) COLLATE pg_catalog."default" NOT NULL,
    eposta character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sifre character varying(15) COLLATE pg_catalog."default" NOT NULL,
    kayittarihi date NOT NULL,
    ad character varying(15) COLLATE pg_catalog."default",
    soyad character varying(15) COLLATE pg_catalog."default",
    roller boolean NOT NULL DEFAULT false,
    CONSTRAINT kullanici_pkey PRIMARY KEY (kullanici_id)
);

CREATE TABLE IF NOT EXISTS public.reklam
(
    reklam_id serial NOT NULL,
    reklam_baslik character varying(100) COLLATE pg_catalog."default" NOT NULL,
    reklam_aciklama character varying(50) COLLATE pg_catalog."default",
    zaman timestamp without time zone NOT NULL,
    goruntulenme_sayisi integer DEFAULT 0,
    CONSTRAINT reklam_pkey PRIMARY KEY (reklam_id)
);

CREATE TABLE IF NOT EXISTS public.reklam_goruntulenme
(
    goruntulenme_id integer NOT NULL DEFAULT nextval('goruntuleme_goruntulenme_id_seq'::regclass),
    reklam_id integer NOT NULL,
    kullanici_id integer NOT NULL,
    CONSTRAINT goruntuleme_pkey PRIMARY KEY (goruntulenme_id)
);

CREATE TABLE IF NOT EXISTS public.yazar
(
    yazar_id serial NOT NULL,
    resim character varying(500) COLLATE pg_catalog."default" NOT NULL,
    bio character varying(500) COLLATE pg_catalog."default" NOT NULL,
    kullanici_id integer,
    CONSTRAINT yazar_pkey PRIMARY KEY (yazar_id)
);

CREATE TABLE IF NOT EXISTS public.yorumlar
(
    yorum_id serial NOT NULL,
    haber_id integer,
    kullanici_id integer,
    yorum character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tarih date NOT NULL,
    CONSTRAINT yorumlar_pkey PRIMARY KEY (yorum_id)
);

ALTER TABLE IF EXISTS public.begeniler
    ADD CONSTRAINT begeniler_haber_id_fkey FOREIGN KEY (haber_id)
    REFERENCES public.haber (haber_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.begeniler
    ADD CONSTRAINT begeniler_kullanici_id_fkey FOREIGN KEY (kullanici_id)
    REFERENCES public.kullanici (kullanici_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.gorseller
    ADD CONSTRAINT gorseller_haber_id_fkey FOREIGN KEY (haber_id)
    REFERENCES public.haber (haber_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.haber
    ADD CONSTRAINT fk_kullanici FOREIGN KEY (kullanici_id)
    REFERENCES public.kullanici (kullanici_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.haber
    ADD CONSTRAINT haber_kategori_id_fkey FOREIGN KEY (kategori_id)
    REFERENCES public.kategoriler (kategori_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.haber
    ADD CONSTRAINT haber_yazar_id_fkey FOREIGN KEY (yazar_id)
    REFERENCES public.yazar (yazar_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.haber_reklam
    ADD CONSTRAINT haber_reklam_haber_id_fkey FOREIGN KEY (haber_id)
    REFERENCES public.haber (haber_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.haber_reklam
    ADD CONSTRAINT haber_reklam_reklam_id_fkey FOREIGN KEY (reklam_id)
    REFERENCES public.reklam (reklam_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.haberetiket
    ADD CONSTRAINT makaleetiket_etiket_id_fkey FOREIGN KEY (etiket_id)
    REFERENCES public.etiketler (etiket_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.haberetiket
    ADD CONSTRAINT makaleetiket_haber_id_fkey FOREIGN KEY (haber_id)
    REFERENCES public.haber (haber_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reklam_goruntulenme
    ADD CONSTRAINT goruntuleme_kullanici_id_fkey FOREIGN KEY (kullanici_id)
    REFERENCES public.kullanici (kullanici_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.reklam_goruntulenme
    ADD CONSTRAINT goruntuleme_reklam_id_fkey FOREIGN KEY (reklam_id)
    REFERENCES public.reklam (reklam_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.yazar
    ADD CONSTRAINT yazar_kullanici_id_fkey FOREIGN KEY (kullanici_id)
    REFERENCES public.kullanici (kullanici_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.yorumlar
    ADD CONSTRAINT yorumlar_haber_id_fkey FOREIGN KEY (haber_id)
    REFERENCES public.haber (haber_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.yorumlar
    ADD CONSTRAINT yorumlar_kullanici_id_fkey FOREIGN KEY (kullanici_id)
    REFERENCES public.kullanici (kullanici_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;